config/routes.rb
Rails.application.routes.draw do
  
  resources :projects, path: :projetos do
    resources :activities, path: :atividades
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'projects#index'
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :project
  validates :name, :begin, :end, presence: { message: "não pode estar em branco"}
  scope :overdue, -> { where(finished: false).order(end: :desc) }
  scope :finished, -> { where(finished: true) }

  def date_overdue
    (self.end > self.project.end && !self.finished) ? "danger" : "body"
  end

  def finalizada
    self.finished ? ["success", "finalizada"] : ["primary", "em andamento"]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :activities, -> { order('finished asc') }, dependent: :destroy
    validates :name, :begin, :end, presence: { message: "não pode estar em branco"}
    validates :name, uniqueness: { message: "tem que ser único"}

    def status
        if self.activities.overdue.first
            data_fim_do_projeto = self.end
            data_atividade_em_andamento = self.activities.overdue.first ? self.activities.overdue.first.end : "finalizado"

            (data_fim_do_projeto < data_atividade_em_andamento) ? ["danger", "ATRASADO"] : ["primary", "EM ANDAMENTO"]
        elsif self.activities.length > 0 && self.activities.overdue.length == 0
            ["success", "COMPLETO"]
        else
            ["light", "NÃO INICIADO"]
        end
    end

    def porcentagem_completa
        if !self.activities.empty?
            porcentagem = (self.activities.finished.length.to_f / self.activities.length.to_f) * 100
            porcentagem.to_i
        else
            0
        end
    end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  before_action :find_project_by_id

  def find_project_by_id
   @project = Project.find_by_id params[:project_id]
  end

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    if @activity.save
      redirect_to project_path(params[:project_id]), notice: 'Atividade criada com sucesso!'
    else
      render :new
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    
      if @activity.update(activity_params)
        redirect_to project_path(params[:project_id]), notice: 'Atividade atualizada com sucesso!'
      else
        render :edit
      end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to project_path(params[:project_id]), notice: 'Atividade destruída com sucesso!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def activity_params
      params.require(:activity).permit(:name, :begin, :end, :finished, :project_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @activities = @project.activities
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Projeto criado com sucesso!' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Projeto atualizado com sucesso!' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Projeto destruído com sucesso!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :begin, :end)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/activities/_form.html.erb
<%= form_with(model: [project, activity], local: true) do |form| %>
  <% if activity.errors.any? %>
    <div id="error_explanation">
      <h2 class="text-danger">Corrija <%= pluralize(activity.errors.count, "error") %> abaixo:</h2>

      <ul>
      <% activity.errors.full_messages.each do |message| %>
        <li class="text-danger"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, "Nome" %>
    <%= form.text_field :name, class: "form-control", :autocomplete => :off %>
  </div>

  <div class="form-row">
    <div class="col">
      <%= form.label :begin, "Início" %>
      <% date = activity.begin ? activity.begin.strftime('%d/%m/%Y') : project.begin.strftime('%d/%m/%Y') %>
      <%= form.text_field :begin, class: "form-control datepicker ", value: date, :autocomplete => :off %>
    </div>

    <div class="col">
      <%= form.label :end, "Fim" %>
      <% date = activity.end ? activity.end.strftime('%d/%m/%Y') : project.begin.next.strftime('%d/%m/%Y') %>
      <%= form.text_field :end, class: "form-control datepicker ", value: date, :autocomplete => :off %>
    </div>
  </div>

  <br>

  <div class="form-group form-check">    
    <%= form.check_box :finished, class: "form-check-input"%>
    <%= form.label :finished, "Finalizada?", class: "form-check-label" %>
  </div>

  <%= form.hidden_field :project_id, value: project.id %>

  <div class="actions">
    <%= form.submit class: "btn btn-primary font-weight-bold btn-sm", value: "Salvar" %>

    <%= link_to 'Cancelar', project_path(project.id), class: "btn btn-danger font-weight-bold btn-sm" %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<div class="container">
    <h1>Editing Activity</h1>

    <%= render 'form', project: @project, activity: @activity %>
</div>

app/views/activities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Activities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Begin</th>
      <th>End</th>
      <th>Finished</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.name %></td>
        <td><%= activity.begin %></td>
        <td><%= activity.end %></td>
        <td><%= activity.finished %></td>
        <td><%= activity.project %></td>
        <td><%= link_to 'Show', activity %></td>
        <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
        <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<div class="container">
    <h1>Adicione uma Atividade</h1>

    <%= render 'form', project: @project, activity: @activity %>
</div>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @activity.name %>
</p>

<p>
  <strong>Begin:</strong>
  <%= @activity.begin %>
</p>

<p>
  <strong>End:</strong>
  <%= @activity.end %>
</p>

<p>
  <strong>Finished:</strong>
  <%= @activity.finished %>
</p>

<p>
  <strong>Project:</strong>
  <%= @activity.project %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Get Things Done!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar d-block">
      <a class="navbar-brand logo" href="/" aria-label="GTD">
        <strong>GET THINGS DONE!</strong>
      </a>

      <%= icon('fas', 'bars', class: "navbar-toggler float-right", "data-toggle": "collapse", "data-target": "#navbarText", "aria-controls": "navbarText", "aria-expanded": "false", "aria-label": "Toggle navigation") %>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <p><a href="" class="nav-link">Sobre</a>
          </li>
          <li class="nav-item">
            <p><a href="" class="nav-link">Contato</a>
          </li>
        </ul>
      </div>
    </nav>
    
    <div class="container-fluid">
      <div class="row">
        
        <div class="col-xl-2 col-lg-1 col-md-0 col-sm-0 col-xs-0">
        </div>

        <div class="col-xl-8 col-lg-10 col-md-12 col-sm-12 col-xs-1 main">
          <br>
          <%= yield %>
          <br>
        </div>

        <div class="col-xl-2 col-lg-1 col-md-0 col-sm-0 col-xs-0">
        </div>

      </div>
    </div>    
    
    <footer class="footer">
      <div class="container-fluid bg-secondary">

        <br/>

        <div class="row text-center">
          <div class="col-3">
            <p><a href="" class="footer-link">Sobre</a>
          </div>

          <div class="col-2">
            <p><a href="" class="footer-link">Contato</a>
          </div>

          <div class="col-1">            
            <a class="footer-icon" href="https://twitter.com/CelsoDeSa">
              <%= icon('fab', "twitter-square") %>
            </a>
          </div>

          <div class="col-2">
            <p><a href="" class="footer-link">Termos</a></p>
          </div>          

          <div class="col-3">
            <p><a href="" class="footer-link">Privacidade</a></p>
          </div>
        </div>

      </div>

      <div class="container-fluid bg-dark">

        <br />

        <div class="row text-center">
          <div class="col-1">
          </div>

          <div class="col-10">
            <p class="disclaimer">COPYRIGHT © <%= Date.current.year %> · GTD &#9733; Todos os direitos reservados</p>
          </div>

          <div class="col-1">
          </div>
        </div>

      </div>
    </footer>

  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2 class="text-danger">Corrija <%= pluralize(project.errors.count, "erro") %> abaixo:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li class="text-danger"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, "Nome" %>
    <%= form.text_field :name, class: "form-control", :autocomplete => :off %>
  </div>

  <div class="form-row">
    <div class="col">
      <%= form.label :begin, "Início" %>
      <% date = project.begin ? project.begin.strftime('%d/%m/%Y') : Date.today.strftime('%d/%m/%Y') %>
      <%= form.text_field :begin, class: "form-control datepicker ", value: date, :autocomplete => :off %>
    </div>

    <div class="col">
      <%= form.label :end, "Fim" %>
      <% date = project.end ? project.end.strftime('%d/%m/%Y') : Date.tomorrow.strftime('%d/%m/%Y') %>
      <%= form.text_field :end, class: "form-control datepicker ", value: date, :autocomplete => :off %>
    </div>
  </div>

  <br>

  <div class="actions">
    <%= form.submit class: "btn btn-primary font-weight-bold btn-sm", value: "Salvar" %>

    <%= link_to 'Cancelar', "/", class: "btn btn-danger font-weight-bold btn-sm" %>

    <% if project.id %>
      <%= link_to 'Ver Atividades', project_path, class: "btn btn-light font-weight-bold btn-sm" %>
    <% end %>
  
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="container">
    <h1>Editing Project</h1>

    <%= render 'form', project: @project %>
</div>

app/views/projects/index.html.erb
<p id="notice" class="text-success"><%= notice %></p>  

<div>
  <div class="row">
    <div class="col">
      <h1>Meus Projetos</h1>
    </div>
  </div>

    <br>

  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th colspan="1">Projeto</th>
        <th colspan="1">Início</th>
        <th colspan="1">Fim</th>
        <th colspan="1">% Completo</th>
        <th colspan="1">Status</th>
        <th colspan="1">
          <%= link_to "+ Projeto", new_project_path, class: "btn btn-info font-weight-bold btn-block btn-sm" %>
        </th>
      </tr>
    </thead>

    <tbody>
      <% @projects.each do |project| %>
        <tr>
          <td>
            <%= link_to project.name, project, class: "text-info font-weight-bold" %>
          </td>
          <td><%= project.begin.strftime('%d/%m/%Y') %></td>
          <td><%= project.end.strftime('%d/%m/%Y') %></td>
          <td>
            <div class="progress" style="height: 25px;">
              <div class="progress-bar" role="progressbar" style="width: <%= project.porcentagem_completa %>%;" aria-valuenow="<%= project.porcentagem_completa %>" aria-valuemin="0" aria-valuemax="100">
                <%= project.porcentagem_completa %>%
              </div>
            </div>
          </td>
          <td>
            <span class="badge badge-pill badge-<%= project.status[0] %>">
              <%= project.status[1] %>
            </span>
          </td>
          <td>
            <div class="float-right">
              <%= link_to icon('fas', 'edit'), edit_project_path(project), class: "btn btn-outline-dark btn-sm" %>
              <%= link_to icon('fas', 'trash-alt'), project, method: :delete, data: { confirm: 'Tem certeza?' }, class: "btn btn-outline-dark btn-sm" %>
            </div>
          </td>
          
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/projects/new.html.erb
<div class="container">
    <h1>Novo Projeto</h1>

    <%= render 'form', project: @project %>
</div>

app/views/projects/show.html.erb
<p id="notice" class="text-success"><%= notice %></p>

  <div>
    <div class="row">
      <div class="col">
        <h1>Atividades do Projeto</h1>
      </div>
    </div>

    <br>

    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th colspan="1">
            <%= link_to  icon('fas', 'edit'), edit_project_path(@project), class: "btn btn-outline-light btn-sm" %>
            <%= @project.name %>
          </th>
          <th colspan="1"><%= @project.begin.strftime('%d/%m/%Y') %></th>
          <th colspan="1"><%= @project.end.strftime('%d/%m/%Y') %></th>
          <th colspan="1">
            <span class="badge badge-pill badge-<%= @project.status[0] %>">
              <%= @project.status[1] %>
          </th>
          <th colspan="1" style="min-width: 100px; width: 15%">      
            <div class="progress" style="height: 25px;">
              <div class="progress-bar" role="progressbar" style="width: <%= @project.porcentagem_completa %>%;" aria-valuenow="<%= @project.porcentagem_completa %>" aria-valuemin="0" aria-valuemax="100">
                <%= @project.porcentagem_completa %>%
              </div>
            </div>
          </th>
        </tr>
      </thead>

      <tbody>
        <% @activities.each do |activity| %>
          <tr>
            <td><%= activity.name %></td>
            <td><%= activity.begin.strftime('%d/%m/%Y') %></td>
            <td class="text-<%= activity.date_overdue %>"><%= activity.end.strftime('%d/%m/%Y') %></td>
            <td>
              <span class="badge badge-pill badge-<%= activity.finalizada[0] %>">
                <%= activity.finalizada[1] %>
              </span>              
            </td>
            <td>
             <div class="float-right">
                <%= link_to icon('fas', 'edit'), edit_project_activity_path(@project, activity), class: "btn btn-outline-dark btn-sm" %>
                <%= link_to icon('fas', 'trash-alt'), project_activity_path(@project, activity), method: :delete, data: { confirm: 'Tem certeza?' }, class: "btn btn-outline-dark btn-sm" %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

  <%= link_to '+ Atividade', new_project_activity_path(@project), class:"btn btn-info font-weight-bold btn-sm" %>
  <%= link_to 'Projetos', "/", class: "btn btn-light" %>
</div>